vscode:
  extensions:
    - rebornix.ruby@0.26.0:RN+gv0dPjYfMqlcEEralhg==
    - castwide.solargraph@0.21.1:kJz6aC6XZbI/EeYHUPNCmQ==
    - ecmel.vscode-html-css@0.2.3:RBTpzQbz8rn5KTlc82tnsQ==
    - rebornix.ruby@0.25.3:EtnhuBkJKfh1e/xxxALcmA==
    - wingrunr21.vscode-ruby@0.26.0:VakXVw0C77hAQ3U3AZTn1Q==
ports:
  - port: 4567
tasks:
 - command: >
      gem install sinatra --no-document
